### ISSUE TITLE
Courses | One paper per step

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#345]
Only one paper button appears per course rather than per step. The most recent paper is replaced anytime you submit a new paper from a different step of the same course.

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/80893226013a4bf53bc0c961f3b688549892d41b

**Comment by EmilyLarkin** [comment]
To add more detail, there should be a way for a paper to be submitted per step. Currently, the issue is that when you submit a paper for any step in the course, the software only allows one paper so it is overwritten continuously. This goes back to [#299](https://github.com/open-learning-exchange/BeLL-Apps/issues/299) and [#289](https://github.com/open-learning-exchange/BeLL-Apps/issues/289).

**Comment by SadiaRasheed** [comment]
The requirement was **that there should be ONLY one paper per step** instead of one paper per course.
Right now this functionality has been implemented as If a learner submits a paper for a step and there is any previously submitted paper already in database for the very step then **that previous paper will be overridden.** 
What is your opinion for this issue? Please write your requirement here.

**Comment by SadiaRasheed** [comment]
This issue is working fine on my side.
here are some screen shots to explain it

**Comment by SadiaRasheed** [comment]
![one paper per step 1](https://cloud.githubusercontent.com/assets/10362799/16764612/9381f644-4848-11e6-8ac2-a5be09a84024.png)
![one paper per step 2](https://cloud.githubusercontent.com/assets/10362799/16764617/98cd9022-4848-11e6-9e16-0d93cf8d6306.png)
[one paper per step 3.txt](https://github.com/open-learning-exchange/BeLL-Apps/files/359127/one.paper.per.step.3.txt)
[one paper per step 4.txt](https://github.com/open-learning-exchange/BeLL-Apps/files/359128/one.paper.per.step.4.txt)

**Comment by SadiaRasheed** [comment]
![one paper per step 1](https://cloud.githubusercontent.com/assets/10362799/16764641/bc4cf02e-4848-11e6-982d-9185a2d41740.png)

---

![one paper per step 2](https://cloud.githubusercontent.com/assets/10362799/16764644/c1e42872-4848-11e6-9e24-6d412bc8905d.png)

**Comment by SadiaRasheed** [comment]
[one paper per step 3.txt](https://github.com/open-learning-exchange/BeLL-Apps/files/359132/one.paper.per.step.3.txt)

[one paper per step 4.txt](https://github.com/open-learning-exchange/BeLL-Apps/files/359133/one.paper.per.step.4.txt)

**Comment by SadiaRasheed** [comment]
![one paper per step 3](https://cloud.githubusercontent.com/assets/10362799/16764682/05406540-4849-11e6-84f2-3351bcd3151d.png)

---

![one paper per step 4](https://cloud.githubusercontent.com/assets/10362799/16764688/0f4142bc-4849-11e6-9fd5-0a9808bedc7d.png)

**Comment by EmilyLarkin** [comment]
![screen shot 2016-07-18 at 3 12 53 pm](https://cloud.githubusercontent.com/assets/15271637/16927138/10f98000-4cfa-11e6-9e19-cbcb88042c55.png)

**Comment by EmilyLarkin** [comment]
So the problem here is that when you look at "Progress" under "Courses", you can see that when you click on one of the student's names, only one paper (the most recent one) appears. The multiple papers may save, but from the instructor side, you cannot access more than one paper per course. This needs to be changed so that there are multiple buttons per step with submitted papers.

**Comment by EmilyLarkin** [comment]
@SadiaRasheed and you can see from the screenshot above that even if I submit multiple papers for a course, only the most recent paper is available and accessible.

**Comment by EmilyLarkin** [comment]
@SadiaRasheed once @dogi gives me a nation for QA tomorrow I'll get back to you on this step FYI (not working on dev but may work on other branch)

**Comment by EmilyLarkin** [comment]
![screen shot 2016-07-20 at 4 25 13 pm](https://cloud.githubusercontent.com/assets/15271637/17001797/7fc516b4-4e96-11e6-9dd1-2a28a9996618.png)

**Comment by EmilyLarkin** [comment]
@SabaBaig @SadiaRasheed so we now have multiple papers as all of the submitted papers are listed. However, there should only be one paper per step. Currently, the paper does not replace the previous paper which means that you can in theory have unlimited paper submissions (which is not what we want). We want one paper per step so that they most recent paper replaces the older paper under progress. Additionally, we need all steps with papers to have their own submission so we don't return to one paper per course.

**Comment by SadiaRasheed** [comment]
@dogi @EmilyLarkin : 
Updates on Issue#345(One paper per step): 
It is working fine on our side (sadia's community, saba's community). Even if you submit multiple papers per step, only one paper (latest submission) exists in database replacing the previous papers.
 I installed new vagrant community from **badges branch** and tested this issue. 
And today I found out the reason that why it is not working on your side. Actually you are not setting the testing environment correctly. There is a view missing from database named as **"assignmentPaperByStepId" which is present only on "badges" branch at the moment**. You need to make sure that it exists in **"assignmentpaper" database** before testing this issue

**Comment by SadiaRasheed** [comment]
![assignment](https://cloud.githubusercontent.com/assets/10362799/17047830/a337ade0-4ffa-11e6-8306-35772ea0cc4e.png)

**Comment by EmilyLarkin** [comment]
![screen shot 2016-07-25 at 3 49 26 pm](https://cloud.githubusercontent.com/assets/15271637/17115042/9c404d44-527f-11e6-8c93-d238b3236ab1.png)

**Comment by EmilyLarkin** [comment]
@SadiaRasheed @SabaBaig When I tested this issue, it does allow for multiple paper uploads, but when you submit multiple papers for the same step, it doesn't replace them. As you can see above, you get multiple papers and you cannot tell which once was accurately for Step 1 (as in the most recent). A resubmitted paper should replace the old paper for that same step. FYI, please be aware that we should still have one paper per step, rather than going back to per course.

**Comment by EmilyLarkin** [comment]
With @dogi's help, we checked the design documents on community and nation. As you can see on the community, the necessary design document is missing. 
![screen shot 2016-07-25 at 4 02 10 pm](https://cloud.githubusercontent.com/assets/15271637/17115408/2e296168-5281-11e6-9fbc-070d6bcdb9fe.png)
On the nation, we have the design document on the nation.
![screen shot 2016-07-25 at 4 03 04 pm](https://cloud.githubusercontent.com/assets/15271637/17115441/4b82aec2-5281-11e6-87d4-c517ff6c3086.png)

**Comment by EmilyLarkin** [comment]
@SadiaRasheed as you know, we create our communities out of the update from the nation and apparently something in there is not working. That's why we put this issue back into Pre-Ready.

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/1cee5dff916dd344a4a3f10653b3d3c4258a0cdb

**Comment by SadiaRasheed** [comment]
I have updated the code for updating design docs. Now when the community will take update from nation, design doc of assignmentpaper database will be updated on community side. I have tested this on my side and it is working fine.

**Comment by EmilyLarkin** [comment]
@SadiaRasheed @dogi I'm still having the error and I reinstalled my testing nation and community after the update. Please see my screenshot below.

**Comment by EmilyLarkin** [comment]
![screen shot 2016-07-27 at 10 21 02 pm](https://cloud.githubusercontent.com/assets/15271637/17199265/88d5486a-5449-11e6-9618-04db9a1eeab6.png)

**Comment by EmilyLarkin** [comment]
@SadiaRasheed @dogi still not working on our end even with an updated nation/community QA installation. See screenshot below

**Comment by EmilyLarkin** [comment]
![screen shot 2016-07-27 at 11 07 22 pm](https://cloud.githubusercontent.com/assets/15271637/17199946/0ba87a50-544f-11e6-8959-27c3acc4d45a.png)

**Comment by umarWaris** [comment]
@EmilyLarkin @dogi i tested this issue on my community, this is working fine
