### ISSUE TITLE
4to6  standard QA test fails

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#95]
![qaprocess](https://cloud.githubusercontent.com/assets/13684059/9828409/ed122f40-58ba-11e5-8259-de5f630135ad.png)
Search is not working anymore after the community got updated by an updated nation

**Comment by MWakas** [comment]
We did try to reproduce this issue on our side,as we updated our 3 machines(communities) with the nbsbell-qa nation(version 0.11.59) but we were unable to reproduce it.Please provide us more details of the issue and the following details as well:
-Nation's name
-Version# on nation(previous and current)
-Version# on the community(previous and current)
-Is search is working on the updated nation(from which the community gets updated)?
-Is search functionality  totally broken or partially broken.
-If the search functionality is partially broken then please provide us with the screenshots of the scenarios in which the search is not working.
_Is there only one community facing this issue or all those communities which get updated with the updated nation?
Additionally the screenshots of the issue will be very helpful to analyze this issue.
Please reply us as you see my comments in here.
Thanks.

**Comment by dogi** [comment]
starting version on community and nation was actual production version 0.11.52 (4to6),
which means all version before more or less failed ... now we are at version 0.11.59
(important QA side info: both nation and community are always already filled with content before updating)
(2nd side info: hope you did not do 1to3 because that worked)

**Comment by MWakas** [comment]
The issue was reproduced on our side and it is fixed now.Here you can find changes in the code on Github:
https://github.com/open-learning-exchange/BeLL-Apps/commit/df257ba36ff846737252b4e704622edcd7339268
https://github.com/open-learning-exchange/BeLL-Apps/commit/7fa96f17fef1512469f1c90544e34679febf4487
The issue has been resolved for other important databases so that it may not arise in future.

**Comment by dogi** [comment]
Hmm
of 10 times updating only twice I was able to do this without error
and both times when I update then the nation true the community
this error is still there - resourceOnTag and searchView are not there

the nation is still online for you (and has the scripts)
http://old.qa.ole.org:5984/apps/_design/bell/MyApp/index.html#dashboard

---
more important
the updateNation script is not working anymore
as you can see on http://earthbell-qa.ole.org:5985/apps/_design/bell/MyApp/index.html#dashboard
which started a nation in version 0.11.52 and got updated

- does not load the toolbar first time logged in

- after refresh 2 grey blocks are blocking the view

- log out does not work so I cleared the browser cache to see the login page

wonder if this new error has something to do with your changes or

**Comment by MWakas** [comment]
The above issue you are on your side is not related to issue#95 or issue#94.This issue is related to the design_docs in configurations database as it appeared in the past as well.Its included in backlog as issue#52.We can start working on issue#52 if you want us so.On the other hand,I removed the design_docs from configurations database on earthbell-qa and its behaving normal now.I cannot test with old.qa as I didn't know the credentials of it.I registered a community(0.11.52) on eathbell-qa(0.11.61) and updated the community with earthbell-qa,it is normal as there were no missing scripts in the community db's.Please test the earthbell-qa on your side and give us the feedback here.Also provide us the credentials of the old.qa nation so that we can test it also.

**Comment by MWakas** [comment]
In addition,there is no problem with update_nation script.Its working fine.If you face any problem with it now please inform us.

**Comment by MWakas** [comment]
In addition the update_nation is all good.There is no problem in it,The problem were arising due to the reason I mentioned in above comment.
